{
  "comments": [
    {
      "key": {
        "uuid": "894e1deb_00c1cc51",
        "filename": "dashboard/dashboard/pinpoint/models/job_state.py",
        "patchSetId": 1
      },
      "lineNbr": 126,
      "author": {
        "id": 1115874
      },
      "writtenOn": "2019-04-03T20:22:33Z",
      "side": 1,
      "message": "Looks like there\u0027s an extra \"source\" after DeadlineExceededError",
      "range": {
        "startLine": 126,
        "startChar": 32,
        "endLine": 126,
        "endChar": 59
      },
      "revId": "48535370ee4b24f332ee318930cbb048b2c2a9b6",
      "serverId": "3ce6091f-6c88-37e8-8c75-72f92ae8dfba",
      "unresolved": true
    }
  ]
}